BUTTON_NAME_MAP = {
    'BTN_NORTH': 'Y',
    'BTN_SOUTH': 'A',
    'BTN_EAST': 'B',
    'BTN_WEST': 'X',
    'BTN_TL': 'LB',
    'BTN_TR': 'RB',
    'BTN_THUMBL': 'LS',
    'BTN_THUMBR': 'RS',
    'BTN_SELECT': 'START',
    'BTN_START': 'SELECT',
    'ABS_RZ': 'RT',
    'ABS_Z': 'LT',
    'ABS_HAT0X_1': 'DPAD_RIGHT',
    'ABS_HAT0X_-1': 'DPAD_LEFT',
    'ABS_HAT0Y_1': 'DPAD_DOWN',
    'ABS_HAT0Y_-1': 'DPAD_UP',
    'ABS_X': 'L_STICK_X',
    'ABS_Y': 'L_STICK_Y',
    'ABS_RX': 'R_STICK_X',
    'ABS_RY': 'R_STICK_Y',
}

CONTROLLER_EVENTS = {
    'BTN_NORTH',
    'BTN_SOUTH',
    'BTN_EAST',
    'BTN_WEST',
    'BTN_TL',
    'BTN_TR',
    'BTN_THUMBL',
    'BTN_THUMBR',
    'BTN_SELECT',
    'BTN_START',
    'ABS_RZ',
    'ABS_Z',
    'ABS_HAT0X',
    'ABS_HAT0Y',
    'ABS_X',
    'ABS_Y',
    'ABS_RX',
    'ABS_RY',
}

JOYSTICK_CUTOFF = 2000
