name: Rust

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # as of right now, this application only supports Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with Cargo
        run: cargo build --verbose
